apiVersion: v1
kind: Service
metadata:
  name: prometheus-server-ext
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
spec:
  selector:
    app: prometheus
    component: server
  ports:
  - port: 9090
    targetPort: 9090
  type: NodePort
