apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: exoexplorer-backend
  namespace: monitoring
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - exoexplorer
  endpoints:
  - port: http          # Ceci doit être le nom du port défini dans votre service, pas un nombre
    path: /actuator/prometheus
    interval: 15s
