apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: exoexplorer
type: Opaque
stringData:
  jasypt-password: "Khaoula2109_"
  jwt-secret: "MyVerySecureJWTSecret123456789"
  spring-mail-password: "nnmz ewom bmzw egfg"
